import type { Metadata } from "next";
import localFont from 'next/font/local';
import "@/styles/globals.css";
import "@/styles/grid.css";

const vazir = localFont({
  src: [
    {
      path: './../../public/fonts/Sahel.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './../../public/fonts/Sahel-Bold.woff',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--font-vazir',
  display: 'swap',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={`${vazir.variable} font-sans`}>
      <body>
        {children}
      </body>
    </html>
  );
}
